### ISSUE TITLE
[sleeping-multi-paxos] Leader maxBallot might change due to RequestPermission from another node 

### ISSUE THREAD

**Issue by kfirdm** [orbs-network/consensus-playground#1]
https://github.com/orbs-network/consensus-playground/blob/bb5969d27897afa22f981863b4cb171e13a05225/src/algorithms/sleeping-multi-paxos/HonestNode.ts#L149

We might want to change (!this.utils.isBallotEqual(this.**maxBallot**, msg.ballot)) to (!this.utils.isBallotEqual(this.**proposedMaxBallot**, msg.ballot)) 
Where this.**proposedMaxBallot** holds the maxBallot the node used in the RequestPermission process.

**Comment by ronentk** [comment]
Related to #2  -I'll look into the protocol definitions to see how they handle the concurrencies

**Comment by ronentk** [comment]
Ok, after reading through some of the [specifications](http://paxos.systems/leader.html) for Multi-Paxos, it seems like indeed the implementation needs to be modified to simulate a multithreaded leader: 

> A leader may work on multiple slots at the same time. For each such slot, the leader selects a command and spawns a new process that we call a commander. While we present it as a separate process, the commander is really just a thread running within the leader.

According to the pseudocode there, a Commander thread is spawned with a given ballot and block, and it records AcceptValue messages with the corresponding ballot,  so this thread isn't directly affected by changes to the max ballot observed by the leader.

In our implementation, this means that for a leader proposing (ballot=b,block=c), replies with ballot=b should be recorded even if the leader has since proposed a new proposal.

I'll finish reading through the protocol and begin work updating our code.

**Comment by ronentk** [comment]
After reading through the rest of the protocol, it seems our implementation is ok-  if the leader hears of a new ballot `b'` higher than that of his proposedMaxBallot `b`, he is _preempted_ ([see pseudocode](http://paxos.systems/leader.html)) and should terminate his attempts to confirm `b` (the Commander threads are terminated), and propose a new ballot. In the original Paxos, this makes sense since pre-emption events are assumed to be rare ([only faulty leaders, network problems, etc..](https://stackoverflow.com/questions/26589137/why-is-multi-paxos-called-multi-paxos)). In our case, we want to change the leader often for fairness, so maybe we would want to make modifications to the protocol. It could have an added advantage of increasing block creation rate (since less proposeValue messages would be needed on average to close a block), but since it deviates from the protocol we would need to make sure security wouldn't be compromised.

In any case, closing this for now as we move on to "Paxos-rand"
